// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/comments": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取需要审核的评论列表",
                "parameters": [
                    {
                        "maximum": 20,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取需要审核的评论列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminCommentReviewList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/comments/:id": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "审核评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "name": "pass",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "审核评论成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/locations": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取需要审核的地点列表",
                "parameters": [
                    {
                        "maximum": 20,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取需要审核的地点列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminLocationReviewList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/locations/:id": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "审核地点",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "name": "pass",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "审核地点成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取应用状态",
                "responses": {
                    "200": {
                        "description": "获取应用状态成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AdminStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UserLoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "刷新访问令牌",
                "responses": {}
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户注册成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/map/location/:id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "获取地点详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取地点详情成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LocationDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/map/location/:id/comments": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "获取地点评论列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "time",
                            "rank"
                        ],
                        "type": "string",
                        "name": "ordered_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_rank",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取地点评论列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.CommentDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "上传评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "上传评论请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UploadCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传评论成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/map/location/view": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "获取指定范围内的地点列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetLocationsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取指定地点列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.LocationDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/map/locations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "上传地点",
                "parameters": [
                    {
                        "description": "上传地点请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UploadLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传地点成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/sse": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "服务器发送事件",
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.CommentDto": {
            "description": "评论的数据结构",
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "location": {
                    "$ref": "#/definitions/dto.LocationDto"
                },
                "rating": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserDto"
                }
            }
        },
        "dto.CommonResponse": {
            "description": "标准返回体结构",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.LocationDto": {
            "description": "地点的数据结构",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "latitude": {
                    "type": "number",
                    "format": "float64"
                },
                "longitude": {
                    "type": "number",
                    "format": "float64"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UserDto": {
            "description": "用户的数据结构",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "nickname": {
                    "type": "string"
                },
                "permissionLevel": {
                    "type": "integer",
                    "format": "int32"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.GetLocationsRequest": {
            "description": "获取地点请求结构体",
            "type": "object",
            "required": [
                "max_lat",
                "max_lng",
                "min_lat",
                "min_lng"
            ],
            "properties": {
                "max_lat": {
                    "type": "number"
                },
                "max_lng": {
                    "type": "number"
                },
                "min_lat": {
                    "type": "number"
                },
                "min_lng": {
                    "type": "number"
                }
            }
        },
        "request.UploadCommentRequest": {
            "description": "上传评论请求结构体",
            "type": "object",
            "required": [
                "content",
                "rating"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 1
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "request.UploadLocationRequest": {
            "description": "上传地点请求结构体",
            "type": "object",
            "required": [
                "address",
                "description",
                "latitude",
                "longitude",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 2
                },
                "description": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 2
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 2
                }
            }
        },
        "request.UserLoginRequest": {
            "description": "用户登录时提交的数据结构",
            "type": "object",
            "required": [
                "password",
                "user_id"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 12
                },
                "user_id": {
                    "description": "用户标识符 可以是UserName 或是邮箱",
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "request.UserRegisterRequest": {
            "description": "用户注册时提交的数据结构",
            "type": "object",
            "required": [
                "email",
                "nickname",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 12
                },
                "username": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "response.AdminCommentReviewList": {
            "description": "管理员评论审核列表响应结构体",
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CommentDto"
                    }
                },
                "has_next": {
                    "type": "boolean"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "response.AdminLocationReviewList": {
            "description": "管理员地点审核列表响应结构体",
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LocationDto"
                    }
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "response.AdminStatusResponse": {
            "description": "管理员状态响应结构体",
            "type": "object",
            "properties": {
                "current_dinner": {
                    "type": "integer"
                },
                "total_dinner": {
                    "type": "integer"
                },
                "total_location": {
                    "type": "integer"
                },
                "total_user": {
                    "type": "integer"
                }
            }
        },
        "response.UserLoginResponse": {
            "description": "用户登录成功后的返回数据结构",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "RiceRise API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
