basePath: /api/v1
definitions:
  dto.CommentDto:
    description: 评论的数据结构
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      location:
        $ref: '#/definitions/dto.LocationDto'
      rating:
        type: integer
      user:
        $ref: '#/definitions/dto.UserDto'
    type: object
  dto.CommonResponse:
    description: 标准返回体结构
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  dto.DinnerDto:
    properties:
      createdAt:
        type: string
      host:
        $ref: '#/definitions/dto.UserDto'
      id:
        type: integer
      location:
        $ref: '#/definitions/dto.LocationDto'
      max:
        type: integer
      meet_time:
        type: string
      participants:
        items:
          $ref: '#/definitions/dto.UserDto'
        type: array
      status:
        type: integer
    type: object
  dto.LocationDto:
    description: 地点的数据结构
    properties:
      address:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    type: object
  dto.UserDto:
    description: 用户的数据结构
    properties:
      createdAt:
        type: string
      id:
        type: integer
      nickname:
        type: string
      permissionLevel:
        type: integer
      username:
        type: string
    type: object
  request.CreateDinnerRequest:
    properties:
      location_id:
        type: integer
      max_people:
        maximum: 64
        minimum: 1
        type: integer
      meet_time:
        type: string
    required:
    - location_id
    - max_people
    - meet_time
    type: object
  request.DinnerRoomChatRequest:
    properties:
      message:
        maxLength: 128
        minLength: 1
        type: string
    required:
    - message
    type: object
  request.GetLocationsRequest:
    description: 获取地点请求结构体
    properties:
      max_lat:
        type: number
      max_lng:
        type: number
      min_lat:
        type: number
      min_lng:
        type: number
    required:
    - max_lat
    - max_lng
    - min_lat
    - min_lng
    type: object
  request.JoinDinnerRequest:
    properties:
      code:
        type: string
    type: object
  request.UpdateDinnerStatusRequest:
    properties:
      status:
        enum:
        - 2
        - 3
        - 4
        type: integer
    required:
    - status
    type: object
  request.UploadCommentRequest:
    description: 上传评论请求结构体
    properties:
      content:
        maxLength: 1024
        minLength: 1
        type: string
      dinnerId:
        type: integer
      rating:
        type: integer
    required:
    - content
    - dinnerId
    - rating
    type: object
  request.UploadLocationRequest:
    description: 上传地点请求结构体
    properties:
      address:
        maxLength: 1024
        minLength: 2
        type: string
      description:
        maxLength: 1024
        minLength: 2
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        maxLength: 128
        minLength: 2
        type: string
    required:
    - address
    - description
    - latitude
    - longitude
    - name
    type: object
  request.UserLoginRequest:
    description: 用户登录时提交的数据结构
    properties:
      password:
        maxLength: 32
        minLength: 12
        type: string
      user_id:
        description: 用户标识符 可以是UserName 或是邮箱
        minLength: 1
        type: string
    required:
    - password
    - user_id
    type: object
  request.UserRegisterRequest:
    description: 用户注册时提交的数据结构
    properties:
      email:
        type: string
      nickname:
        maxLength: 64
        minLength: 8
        type: string
      password:
        maxLength: 32
        minLength: 12
        type: string
      username:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - nickname
    - password
    - username
    type: object
  response.AdminCommentReviewList:
    description: 管理员评论审核列表响应结构体
    properties:
      comments:
        items:
          $ref: '#/definitions/dto.CommentDto'
        type: array
      has_next:
        type: boolean
      page_size:
        type: integer
    type: object
  response.AdminLocationReviewList:
    description: 管理员地点审核列表响应结构体
    properties:
      has_next:
        type: boolean
      locations:
        items:
          $ref: '#/definitions/dto.LocationDto'
        type: array
      page_size:
        type: integer
    type: object
  response.AdminStatusResponse:
    description: 管理员状态响应结构体
    properties:
      current_dinner:
        type: integer
      total_dinner:
        type: integer
      total_location:
        type: integer
      total_user:
        type: integer
    type: object
  response.InviteCodeResponse:
    properties:
      code:
        type: string
    type: object
  response.UserLoginResponse:
    description: 用户登录成功后的返回数据结构
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/dto.UserDto'
    type: object
info:
  contact: {}
  title: RiceRise API
  version: "1.0"
paths:
  /admin/comments:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        maximum: 20
        minimum: 1
        name: page_size
        type: integer
      - in: query
        name: start_id
        type: integer
      - in: query
        name: start_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取需要审核的评论列表成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.AdminCommentReviewList'
              type: object
      summary: 获取需要审核的评论列表
      tags:
      - admin
  /admin/comments/:id:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 评论ID
        in: path
        name: id
        required: true
        type: integer
      - in: query
        name: pass
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 审核评论成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 审核评论
      tags:
      - admin
  /admin/locations:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        maximum: 20
        minimum: 1
        name: page_size
        type: integer
      - in: query
        name: start_id
        type: integer
      - in: query
        name: start_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取需要审核的地点列表成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.AdminLocationReviewList'
              type: object
      summary: 获取需要审核的地点列表
      tags:
      - admin
  /admin/locations/:id:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 地点ID
        in: path
        name: id
        required: true
        type: integer
      - in: query
        name: pass
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 审核地点成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 审核地点
      tags:
      - admin
  /admin/status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 获取应用状态成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.AdminStatusResponse'
              type: object
      summary: 获取应用状态
      tags:
      - admin
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登录请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 用户登录成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserLoginResponse'
              type: object
      summary: 用户登录
      tags:
      - user
  /auth/refresh:
    post:
      responses: {}
      summary: 刷新访问令牌
      tags:
      - user
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户注册请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 用户注册成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 用户注册
      tags:
      - user
  /dinners:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.DinnerDto'
              type: object
      summary: 获取未结束/取消的饭局
      tags:
      - dinner
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建饭局请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateDinnerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 修改状态成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.DinnerDto'
              type: object
      summary: 创建饭局
      tags:
      - dinner
  /dinners/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取饭局详情成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.DinnerDto'
              type: object
      summary: 获取饭局详情
      tags:
      - dinner
    patch:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新状态请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateDinnerStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 修改状态成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 修改饭局状态
      tags:
      - dinner
  /dinners/:id/code:
    get:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 创建邀请码成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.InviteCodeResponse'
              type: object
      summary: 生成饭局邀请码
      tags:
      - dinner
  /dinners/:id/messages:
    post:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      - description: 饭局聊天请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DinnerRoomChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 发送消息成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 饭局内聊天
      tags:
      - dinner
  /dinners/:id/participants/:
    post:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      - description: 加入饭局请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.JoinDinnerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 加入饭局成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.DinnerDto'
              type: object
      summary: 加入约饭
      tags:
      - dinner
  /dinners/:id/participants/me:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 饭局ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 退出约饭成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 退出约饭
      tags:
      - dinner
  /map/location/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: 地点ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取地点详情成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.LocationDto'
              type: object
      summary: 获取地点详情
      tags:
      - map
  /map/location/:id/comments:
    get:
      consumes:
      - application/json
      parameters:
      - description: 地点ID
        in: path
        name: id
        required: true
        type: integer
      - enum:
        - time
        - rank
        in: query
        name: ordered_by
        type: string
      - in: query
        name: page_size
        type: integer
      - in: query
        name: start_id
        type: integer
      - in: query
        name: start_rank
        type: integer
      - in: query
        name: start_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取地点评论列表成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.CommentDto'
                  type: array
              type: object
      summary: 获取地点评论列表
      tags:
      - map
    post:
      consumes:
      - application/json
      parameters:
      - description: 地点ID
        in: path
        name: id
        required: true
        type: integer
      - description: 上传评论请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UploadCommentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 上传评论成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 上传评论
      tags:
      - map
  /map/location/view:
    post:
      consumes:
      - application/json
      parameters:
      - description: 查询参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.GetLocationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 获取指定地点列表成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.LocationDto'
                  type: array
              type: object
      summary: 获取指定范围内的地点列表
      tags:
      - map
  /map/locations:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取地点搜索结果成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.LocationDto'
                  type: array
              type: object
      summary: 搜索地点
      tags:
      - map
    post:
      consumes:
      - application/json
      parameters:
      - description: 上传地点请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UploadLocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 上传地点成功
          schema:
            $ref: '#/definitions/dto.CommonResponse'
      summary: 上传地点
      tags:
      - map
  /sse:
    get:
      responses: {}
      summary: 服务器发送事件
      tags:
      - user
  /user/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserDto'
              type: object
      summary: 获取当前用户信息
      tags:
      - user
schemes:
- http
- https
swagger: "2.0"
